on:
  push:
    branches:
      - master

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Register .env
      working-directory: ./server
      env:
        FFMPEG_PATH: ${{ secrets.FFMPEG_PATH }}
        FFPROBE_PATH: ${{ secrets.FFPROBE_PATH }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
      run: |
        echo "FFMPEG_PATH=${FFMPEG_PATH}" >> ./.env
        echo "FFPROBE_PATH=${FFPROBE_PATH}" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}" >> ./.env
    - name: Register firebaseConfig.json
      working-directory: ./server
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: |
        echo "${FIREBASE_CONFIG}" >> ./firebaseConfig.json
    - name: yarn install
      working-directory: ./server
      run: yarn install
    - name: serverless package and deploy
      working-directory: ./server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn run serverless package --stage production --package ./build
        yarn run serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        yarn run serverless deploy --stage production --package ./build
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: server/build